import type { Config } from 'tailwindcss'
import tailwindcssAnimate from 'tailwindcss-animate'
import { fontFamily } from 'tailwindcss/defaultTheme'

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: {
      inherit: 'inherit',
      transparent: 'transparent',
      current: 'currentColor',

      background: 'hsl(var(--background))',
      foreground: 'hsl(var(--foreground))',
      card: {
        DEFAULT: 'hsl(var(--card))',
        foreground: 'hsl(var(--card-foreground))',
      },
      popover: {
        DEFAULT: 'hsl(var(--popover))',
        foreground: 'hsl(var(--popover-foreground))',
      },
      muted: {
        DEFAULT: 'hsl(var(--muted))',
        foreground: 'hsl(var(--muted-foreground))',
      },
      accent: {
        DEFAULT: 'hsl(var(--accent))',
        foreground: 'hsl(var(--accent-foreground))',
      },
      destructive: {
        DEFAULT: 'hsl(var(--destructive))',
        foreground: 'hsl(var(--destructive-foreground))',
      },
      border: 'hsl(var(--border))',
      input: 'hsl(var(--input))',
      ring: 'hsl(var(--ring))',
      black: 'hsl(var(--black))',
      white: 'hsl(var(--white))',
      grey: {
        50: 'hsl(var(--grey-50))',
        100: 'hsl(var(--grey-100))',
        200: 'hsl(var(--grey-200))',
        300: 'hsl(var(--grey-300))',
        400: 'hsl(var(--grey-400))',
        500: 'hsl(var(--grey-500))',
        600: 'hsl(var(--grey-600))',
        700: 'hsl(var(--grey-700))',
        800: 'hsl(var(--grey-800))',
        900: 'hsl(var(--grey-900))',
      },
      primary: {
        DEFAULT: 'hsl(var(--primary))',
        foreground: 'hsl(var(--primary-foreground))',
        50: 'hsl(var(--primary-50))',
        100: 'hsl(var(--primary-100))',
        200: 'hsl(var(--primary-200))',
        300: 'hsl(var(--primary-300))',
        400: 'hsl(var(--primary-400))',
        500: 'hsl(var(--primary-500))',
        600: 'hsl(var(--primary-600))',
        700: 'hsl(var(--primary-700))',
        800: 'hsl(var(--primary-800))',
        900: 'hsl(var(--primary-900))',
      },
      secondary: {
        DEFAULT: 'hsl(var(--secondary))',
        foreground: 'hsl(var(--secondary-foreground))',
        50: 'hsl(var(--secondary-50))',
        100: 'hsl(var(--secondary-100))',
        200: 'hsl(var(--secondary-200))',
        300: 'hsl(var(--secondary-300))',
        400: 'hsl(var(--secondary-400))',
        500: 'hsl(var(--secondary-500))',
        600: 'hsl(var(--secondary-600))',
        700: 'hsl(var(--secondary-700))',
        800: 'hsl(var(--secondary-800))',
        900: 'hsl(var(--secondary-900))',
      },
      success: {
        DEFAULT: 'hsl(var(--success-500))',
        50: 'hsl(var(--success-50))',
        100: 'hsl(var(--success-100))',
        200: 'hsl(var(--success-200))',
        300: 'hsl(var(--success-300))',
        400: 'hsl(var(--success-400))',
        500: 'hsl(var(--success-500))',
        600: 'hsl(var(--success-600))',
        700: 'hsl(var(--success-700))',
        800: 'hsl(var(--success-800))',
        900: 'hsl(var(--success-900))',
      },
      info: {
        DEFAULT: 'hsl(var(--info-500))',
        50: 'hsl(var(--info-50))',
        100: 'hsl(var(--info-100))',
        200: 'hsl(var(--info-200))',
        300: 'hsl(var(--info-300))',
        400: 'hsl(var(--info-400))',
        500: 'hsl(var(--info-500))',
        600: 'hsl(var(--info-600))',
        700: 'hsl(var(--info-700))',
        800: 'hsl(var(--info-800))',
        900: 'hsl(var(--info-900))',
      },
      warning: {
        DEFAULT: 'hsl(var(--warning-500))',
        50: 'hsl(var(--warning-50))',
        100: 'hsl(var(--warning-100))',
        200: 'hsl(var(--warning-200))',
        300: 'hsl(var(--warning-300))',
        400: 'hsl(var(--warning-400))',
        500: 'hsl(var(--warning-500))',
        600: 'hsl(var(--warning-600))',
        700: 'hsl(var(--warning-700))',
        800: 'hsl(var(--warning-800))',
        900: 'hsl(var(--warning-900))',
      },
      error: {
        DEFAULT: 'hsl(var(--error-500))',
        50: 'hsl(var(--error-50))',
        100: 'hsl(var(--error-100))',
        200: 'hsl(var(--error-200))',
        300: 'hsl(var(--error-300))',
        400: 'hsl(var(--error-400))',
        500: 'hsl(var(--error-500))',
        600: 'hsl(var(--error-600))',
        700: 'hsl(var(--error-700))',
        800: 'hsl(var(--error-800))',
        900: 'hsl(var(--error-900))',
      },
    },
    extend: {
      boxShadow: {
        sm: '0px 7px 29px 0px rgba(100, 100, 111, 0.20)',
        md: '0px 6px 12px 0px rgba(0, 0, 0, 0.16)',
      },
      fontFamily: {
        prompt: ['var(--font-prompt)', ...fontFamily.sans],
      },
      borderRadius: {
        '2xl': 'calc(var(--radius) + 4px)',
        xl: 'calc(var(--radius) + 2px)',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      backgroundImage: {
        'primary-gradient':
          'linear-gradient(180deg, hsla(16, 99%, 60%, 1) 68%, hsla(34, 87%, 60%, 1) 100%)',
        'reverse-primary-gradient':
          'linear-gradient(0deg, hsla(16, 99%, 60%, 1) 68%, hsla(34, 87%, 60%, 1) 100%)',
        'background-gradient':
          'linear-gradient(180deg, hsla(25, 100%, 84%, 1) 34.5%, hsla(43, 97%, 84%, 1) 73%, hsla(48, 45%, 98%, 1) 100%)',
      },
    },
  },
  plugins: [tailwindcssAnimate],
}
export default config
