definitions:
  domain.Address:
    properties:
      district:
        type: string
      house_no:
        type: string
      postcode:
        type: string
      province:
        type: string
    type: object
  domain.PaymentMethod:
    properties:
      card_number:
        type: string
      card_owner:
        type: string
      cvv:
        type: string
      expire_date:
        type: string
    type: object
  domain.User:
    properties:
      address:
        $ref: '#/definitions/domain.Address'
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      last_name:
        type: string
      payment_method:
        $ref: '#/definitions/domain.PaymentMethod'
      tel:
        type: string
    type: object
  domain.UserCreateBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Shanepee API
  title: Shanepee API
  version: "0.0"
paths:
  /v1/auth/register:
    post:
      description: Register
      parameters:
      - description: user create body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.UserCreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Register User
      tags:
      - Authentication
  /v1/user/:id:
    patch:
      consumes:
      - application/json
      description: update user by id
      parameters:
      - description: id of user to be updated
        in: path
        name: id
        required: true
        type: integer
      - description: body of user to be updated
        in: body
        name: body
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Update User
      tags:
      - User
swagger: "2.0"
