definitions:
  domain.A:
    properties:
      id:
        type: integer
      long_data:
        type: string
        x-nullable: true
    type: object
  domain.ACreateBody:
    properties:
      long_data:
        type: string
        x-nullable: true
    type: object
  domain.Address:
    properties:
      district:
        type: string
        x-nullable: true
      house_no:
        type: string
        x-nullable: true
      postcode:
        type: string
        x-nullable: true
      province:
        type: string
        x-nullable: true
    type: object
  domain.PaymentMethod:
    properties:
      card_number:
        type: string
        x-nullable: true
      card_owner:
        type: string
        x-nullable: true
      cvv:
        type: string
        x-nullable: true
      expire_date:
        type: string
        x-nullable: true
    type: object
  domain.User:
    properties:
      address:
        $ref: '#/definitions/domain.Address'
      email:
        type: string
      first_name:
        type: string
        x-nullable: true
      gender:
        type: string
        x-nullable: true
      id:
        type: integer
      last_name:
        type: string
        x-nullable: true
      payment_method:
        $ref: '#/definitions/domain.PaymentMethod'
      tel:
        type: string
        x-nullable: true
    type: object
  domain.UserCreateBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Shanepee API
  title: Shanepee API
  version: "0.0"
paths:
  /v1/a:
    get:
      description: get A
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.A'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: get A
      tags:
      - A
    post:
      consumes:
      - application/json
      description: create A
      parameters:
      - description: A body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.ACreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.A'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: create A
      tags:
      - A
  /v1/a/:id:
    delete:
      consumes:
      - application/json
      description: delete A
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: delete A
      tags:
      - A
    get:
      description: get A
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.A'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: get A
      tags:
      - A
    patch:
      consumes:
      - application/json
      description: update A
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: A body
        in: body
        name: body
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.A'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: update A
      tags:
      - A
  /v1/auth/register:
    post:
      description: Register
      parameters:
      - description: user create body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.UserCreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Register User
      tags:
      - Authentication
swagger: "2.0"
