definitions:
  domain.A:
    properties:
      id:
        type: integer
      long_data:
        type: string
    type: object
  domain.ACreateBody:
    properties:
      long_data:
        type: string
    type: object
  domain.Address:
    properties:
      district:
        type: string
      house_no:
        type: string
      postcode:
        type: string
      province:
        type: string
    type: object
  domain.PaymentMethod:
    properties:
      card_number:
        type: string
      card_owner:
        type: string
      cvv:
        type: string
      expire_date:
        type: string
    type: object
  domain.User:
    properties:
      address:
        $ref: '#/definitions/domain.Address'
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      last_name:
        type: string
      paymentMethod:
        $ref: '#/definitions/domain.PaymentMethod'
      tel:
        type: string
    type: object
  domain.UserCreateBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Shanepee API
  title: Shanepee API
  version: "0.0"
paths:
  /v1/a:
    get:
      description: get A
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.A'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: get A
      tags:
      - a
    post:
      consumes:
      - application/json
      description: create A
      parameters:
      - description: A body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.ACreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.A'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: create A
      tags:
      - a
  /v1/auth/register:
    post:
      description: Register
      parameters:
      - description: user create body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.UserCreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Register User
      tags:
      - Authentication
swagger: "2.0"
