// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shanepee.com/api/config"
	"shanepee.com/api/infrastructure/handler"
	"shanepee.com/api/infrastructure/repository"
	"shanepee.com/api/service"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return App{}, err
	}
	db, err := repository.NewDB(configConfig)
	if err != nil {
		return App{}, err
	}
	aRepository := repository.NewARepository(db)
	aService := service.NewAService(aRepository)
	aHandler := handler.NewAHandler(aService)
	authRepository := repository.NewAuthRepository(db)
	authService := service.NewAuthService(authRepository)
	authHandler := handler.NewAuthHandler(authService)
	app := NewApp(aHandler, authHandler, configConfig)
	return app, nil
}
