// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shanepee.com/api/config"
	"shanepee.com/api/infrastructure/handler"
	"shanepee.com/api/infrastructure/repository"
	"shanepee.com/api/infrastructure/session"
	"shanepee.com/api/service"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return App{}, err
	}
	db, err := repository.NewDB(configConfig)
	if err != nil {
		return App{}, err
	}
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(userRepository)
	defaultOptions := session.NewDefaultOptions(configConfig)
	authHandler := handler.NewAuthHandler(authService, defaultOptions)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	store := session.NewStore(configConfig, defaultOptions, db)
	app := NewApp(authHandler, userHandler, configConfig, store)
	return app, nil
}
