// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shanepee.com/api/config"
	"shanepee.com/api/infrastructure/email"
	"shanepee.com/api/infrastructure/handler"
	"shanepee.com/api/infrastructure/repository"
	"shanepee.com/api/infrastructure/session"
	"shanepee.com/api/service"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return App{}, err
	}
	db, err := repository.NewDB(configConfig)
	if err != nil {
		return App{}, err
	}
	userRepository := repository.NewUserRepository(db)
	emailSender := email.NewEmailSender(configConfig)
	authService := service.NewAuthService(userRepository, emailSender)
	options := session.NewOptions(configConfig)
	authHandler := handler.NewAuthHandler(authService, options)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	artToyRepository := repository.NewArtToyRepository(db)
	artToyService := service.NewArtToyService(artToyRepository)
	artToyHandler := handler.NewArtToyHandler(artToyService)
	store := session.NewStore(configConfig, options, db)
	app := NewApp(authHandler, userHandler, artToyHandler, configConfig, store)
	return app, nil
}
