import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'

import { Footer } from '@/components/footer'
import { Toaster } from '@/components/toast'

import { CartProvider } from '@/providers/cart-provider'
import { UserProvider } from '@/providers/user-provider'

import { cn } from '@/lib/utils'

import '@/styles/globals.css'

import { NavbarContainer } from './_containers/navbar-container'

const prompt = Prompt({
  subsets: ['latin', 'thai'],
  variable: '--font-prompt',
  weight: ['400', '600'],
})

// TODO: Add your own metadata
export const metadata: Metadata = {
  title: 'ShanePee',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn('min-h-dvh font-prompt antialiased', prompt.variable)}
      >
        <UserProvider>
          <CartProvider>
            <NavbarContainer />
            <main className='min-h-[calc(100dvh-62px-256px)]'>{children}</main>
            <Footer />
            <Toaster richColors />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  )
}
