// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shanepee.com/api/infrastructure/handler"
	"shanepee.com/api/infrastructure/repository"
	"shanepee.com/api/service"
)

import (
	_ "shanepee.com/api/docs"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	aRepository := repository.NewARepository()
	aService := service.NewAService(aRepository)
	aHandler := handler.NewAHandler(aService)
	app := NewApp(aHandler)
	return app, nil
}
