name: API Lint

on:
  pull_request:
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
    paths:
      - "api/**"
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
          cache-dependency-path: api/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: api
          args: --timeout=10m
